[general]
# Relative or absolute BIOS file.
bios_file = "bios.bin"
# Skips the BIOS intro.
bios_skip = false
# Relative or absolute save directory.
# An empty value stores save files next to the ROM.
save_dir = ""
# Controller deadzone.
deadzone = 16000

# Custom multipliers can be used to alter the refresh rate of 
# 59.737Hz. This also affects the event processing frequency.
[multipliers]
fps_multiplier_1 = 2.0
fps_multiplier_2 = 4.0
fps_multiplier_3 = 6.0
fps_multiplier_4 = 8.0

# The following sections contain custom [keyboard, controller]
# mappings. An empty value creates no mapping.
# Possible keyboard values: https://github.com/SDL-mirror/SDL/blob/master/src/events/SDL_keyboard.c#L282
# Possible controller values: https://github.com/SDL-mirror/SDL/blob/master/src/joystick/SDL_gamecontroller.c#L492
[controls]
a      = ["U", "B"            ]
b      = ["H", "A"            ]
up     = ["W", "DPUP"         ]
down   = ["S", "DPDOWN"       ]
left   = ["A", "DPLEFT"       ]
right  = ["D", "DPRIGHT"      ]
start  = ["F", "BACK"         ]
select = ["G", "START"        ]
l      = ["Q", "LEFTSHOULDER" ]
r      = ["I", "RIGHTSHOULDER"]

[shortcuts]
reset         = ["R"  , ""]
fullscreen    = ["F11", ""]
fps_default   = ["1"  , ""]
fps_option_1  = ["2"  , ""]
fps_option_2  = ["3"  , ""]
fps_option_3  = ["4"  , ""]
fps_option_4  = ["5"  , ""]
fps_unlimited = ["6"  , ""]
