[general]
save_path = ""
bios_file = ""
bios_skip = true

[framerate]
custom_1 = 119.474
custom_2 = 238.948
custom_3 = 358.442
custom_4 = 477.896

[controls]
a      = ["U", "B"    ]
b      = ["H", "A"    ]
up     = ["W", "UP"   ]
down   = ["S", "DOWN" ]
left   = ["A", "LEFT" ]
right  = ["D", "RIGHT"]
start  = ["G", "START"]
select = ["F", "BACK" ]
l      = ["Q", "L"    ]
r      = ["I", "R"    ]

[shortcuts]
reset       = ["R"  , ""]
fullscreen  = ["F11", ""]
fr_hardware = ["1"  , ""]
fr_custom_1 = ["2"  , ""]
fr_custom_2 = ["3"  , ""]
fr_custom_3 = ["4"  , ""]
fr_custom_4 = ["5"  , ""]
fr_unbound  = ["6"  , ""]
