[general]
# Relative or absolute BIOS file.
bios_file = "bios.bin"
# Skips the BIOS intro.
bios_skip = false
# Relative or absolute save directory. An empty
# value stores save files next to the ROM.
save_dir = ""
# Controller deadzone.
deadzone = 16000

# Custom multipliers used to alter the refresh rate
# of 59.737Hz. This also affects event processing.
[multipliers]
fps_multiplier_1 = 2.0
fps_multiplier_2 = 4.0
fps_multiplier_3 = 6.0
fps_multiplier_4 = 8.0

# Custom [keyboard, controller] mappings. An empty
# value creates no mapping.
# Possible values: https://github.com/jsmolka/eggvance/blob/master/eggvance/src/common/input.cpp
[controls]
a      = ["U", "B"            ]
b      = ["H", "A"            ]
up     = ["W", "DPUP"         ]
down   = ["S", "DPDOWN"       ]
left   = ["A", "DPLEFT"       ]
right  = ["D", "DPRIGHT"      ]
start  = ["G", "START"        ]
select = ["F", "BACK"         ]
l      = ["Q", "LEFTSHOULDER" ]
r      = ["I", "RIGHTSHOULDER"]

[shortcuts]
reset         = ["R"  , ""]
fullscreen    = ["F11", ""]
fps_default   = ["1"  , ""]
fps_custom_1  = ["2"  , ""]
fps_custom_2  = ["3"  , ""]
fps_custom_3  = ["4"  , ""]
fps_custom_4  = ["5"  , ""]
fps_unlimited = ["6"  , ""]
